blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("category/<cat>/", views.CategoryView.as_view(), name="category"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("article/<str:category>/<slug:slug>/", views.articleView, name="article"),
    path("show-content/", views.showContent, name="content"),
    path("cat-show-content/", views.catShowContent, name="catcontent"),
    path("fake-news/", views.fake_news, name="fake-news"),
    path('predict/', views.predict, name='predict')
]

tribune/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("blog.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

from django.utils.text import slugify

from .utils import generate_unique_slug

# from cloudinary.models import CloudinaryField


# You can create your models here.
class Category(models.Model):
    name = models.CharField(max_length=55)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Blog(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, db_index=True)
    description = models.CharField(max_length=160)
    photo_main = models.ImageField(upload_to="uploads/%Y/%m")
    slug = models.SlugField(max_length=200, unique=True, editable=False)
    content = models.TextField()
    views = models.IntegerField(default=0)
    list_date = models.DateTimeField(default=datetime.now)
    is_published = models.BooleanField(default=True)

    class Meta:
        ordering = ["-list_date"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = generate_unique_slug(Blog, self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "blog:article", kwargs={"category": self.category, "slug": self.slug}
        )

blog/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import F
from django.http import JsonResponse
from django.http import QueryDict

import joblib
import re
import string
from django.views.decorators.csrf import csrf_exempt

from .models import Blog

def wordppt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W", " ", text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text


def output_label(n):
    if n == 0:
        return 'Fake News'
    elif n == 1:
        return 'Not A Fake News'


# You can create your views here.
class IndexView(ListView):
    context_object_name = "blogs"
    template_name = "blog/index.html"

    def get_queryset(self):
        return Blog.objects.filter(is_published=True).only(
            "title", "category", "photo_main", "list_date", "description", "slug"
        )[:25]


class CategoryView(ListView):
    template_name = "blog/category.html"
    context_object_name = "blogs"

    def get_queryset(self):
        cat = self.kwargs.get("cat")
        blog = (
            Blog.objects.filter(is_published=True)
            .filter(category__name=cat)
            .only(
                "title", "category", "photo_main", "list_date", "description", "slug"
            )[:25]
        )
        return get_list_or_404(blog)


def articleView(request, category, slug):
    article = get_object_or_404(Blog, slug=slug)
    Blog.objects.filter(slug=slug).update(views=F("views") + 1)
    context = {}
    context["articles"] = (
        Blog.objects.filter(is_published=True)
        .order_by("-list_date")
        .only("title", "photo_main", "slug")[:12]
    )
    context["blog"] = article
    return render(request, "blog/article.html", context)


class SearchView(ListView):
    template_name = "blog/search.html"
    context_object_name = "blogs"
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get("q", "")
        return Blog.objects.filter(is_published=True).filter(title__icontains=query)


def showContent(request):
    # Get length of queryset
    if request.is_ajax():
        count = Blog.objects.filter(is_published=True).count()
        print(count)
        context = {}
        start = int(request.GET.get("start"))
        end = int(request.GET.get("end"))

        posts = Blog.objects.filter(is_published=True).only(
            "title", "category", "description", "list_date", "photo_main", "slug"
        )[start : end + 1]

        context["last"] = False
        if start > count:
            context["last"] = True
        context["posts"] = posts
        return render(request, "blog/data.html", context)
    return render(request, "404.html", status=404)


def catShowContent(request):
    if request.is_ajax():
        cat = request.GET.get("cat")
        start = int(request.GET.get("start"))
        end = int(request.GET.get("end"))
        count = (
            Blog.objects.filter(is_published=True).filter(category__name=cat).count()
        )

        context = {}
        posts = (
            Blog.objects.filter(is_published=True)
            .filter(category__name=cat)
            .only(
                "title", "category", "description", "list_date", "photo_main", "slug"
            )[start : end + 1]
        )

        context["last"] = False
        if start > count:
            context["last"] = True
        context["posts"] = posts
        return render(request, "blog/data.html", context)


def fake_news(request):
    return render(request, "blog/fake-news.html")

@csrf_exempt
def predict(request):
    if request.method == 'GET':
        text = request.GET.get('text')

        LR = joblib.load('./blog/algorithm/dt.joblib')
        DT = joblib.load('./blog/algorithm/dt.joblib')
        GB = joblib.load('./blog/algorithm/gb.joblib')
        RF = joblib.load('./blog/algorithm/rf.joblib')
        vectorization = joblib.load('./blog/algorithm/vectorization.joblib')

        text_cleaned = wordppt(text)
        new_x_test = [text_cleaned]
        new_xv_test = vectorization.transform(new_x_test)

        pred_LR = LR.predict(new_xv_test)
        pred_DT = DT.predict(new_xv_test)
        pred_GB = GB.predict(new_xv_test)
        pred_RF = RF.predict(new_xv_test)

        
        return JsonResponse({
            'LR': output_label(pred_LR[0]),
            'DT': output_label(pred_DT[0]),
            'GB':  output_label(pred_GB[0]),
            'RF':  output_label(pred_RF[0])
        })

blog/templates/blog/article.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load trendings %}

{% block content %}
    
  <main id="tribune-content" class="wrapper container-fluid">
    
    <div class="content-wrapper bg-white">
      <!-- main content -->
      <div class="main-content">
        <div class="article-heading">
          <a href="{% url 'blog:category' blog.category %}">{{ blog.category|title }}</a>
          <small class="post-time">
            · Posted {{ blog.list_date|naturaltime }}
          </small> 
          <div class="social-share-icons">
            <i class="fab fa-facebook" onclick="shareFacebook();"></i>
            <i class="fab fa-twitter" onclick="shareTwitter();"></i>
            <i class="fab fa-pinterest" onclick="sharePinterest();"></i>
            <i class="fab fa-google-plus" onclick="shareGoogle();"></i>
          </div>
          <div class="article-title">
            <h2>{{ blog.title|title }}</h2>
          </div>
        </div>

        <div class="article-content">
          <div class="card-img">
            <img data-src="{{ blog.photo_main.url }}" alt="">
          </div>
          <div class="article-body">
            {{ blog.content|safe }}
              
            </div>
          </div>
        </div>
        <div class="aside-content">
          <!-- Trending -->
          <div id="trending-list" class="bg-white mb-2 sider">
            <h2 class="trending-title">
              <i class="fas fa-chart-line"></i> Trending
            </h2>
            <div class="card news">
              {% show_trendings %}
            </div>
          </div>
          <!-- End of trending -->
        </div>
    </div>
    <!-- end of main content -->

    <!-- Recommendations -->
    <div class="divider"></div>

    <div class="recommendation bg-white mb-2">
      <h2 class="recom-heading">More From Tribune States</h2>
      
      <div class="recommendation-wrapper">
        {% for article in articles %}
          <!-- single recommendation -->
          <article class="recom-article card">
            <div class="card-img">
              <img data-src="{{ article.photo_main.url }}" alt="">
            </div>
              <a href="{% url 'blog:article' article.category article.slug %}" class="recom-title">
                <h2>{{ article.title|title }}</h2>
              </a>
          </article>
          <!-- end of single recommendation -->
        {% endfor %}
      </div>
    </div>
  </main>
{% endblock %}

blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load trendings %}

{% block content %}
    
  <main id="tribune-content" class="wrapper container-fluid">
    <div class="category-heading">
      <h1>TRIBUNE STATES</h1>
    </div>

    <!-- title -->
    <h2 class="category-title">
      {{ blogs.0.category|upper }}
    </h2>
    <!-- end of title -->
    <div class="featured-section bg-white">
      <div class="latest-news featured-item">
        <h3>Latest News</h3>
        <ul class="latest-news-items">
          {% for blog in blogs|slice:'2:6' %}
          <li>
            <a href="{% url 'blog:article' blog.category blog.slug %}">
            {{ blog.title|title }}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>

      <!-- main card -->
      <article class="trending pb-2 featured-item card">
        <div class="card-img">
          <img data-src="{{ blogs.0.photo_main.url }}" alt="">
        </div>
        <div class="card-body">
          <a href="{% url 'blog:article' blogs.0.category blogs.0.slug %}" class="card-title">
            <h2>{{ blogs.0.title }}</h2>
          </a>
        </div>

      </article>
      <!-- end of main card -->

      <!-- main card -->
      <article class="trending pb-2 featured-item card">
        <div class="card-img">
          <img data-src="{{ blogs.1.photo_main.url }}" alt="">
        </div>
        <div class="card-body">
          <a href="{% url 'blog:article' blogs.1.category blogs.1.slug %}" class="card-title">
            <h2>{{ blogs.1.title }}</h2>
          </a>
        </div>

      </article>
      <!-- end of main card -->
    </div>

    <div class="content-wrapper bg-white mb-2">
      <div class="main-content">
         <!-- article listings -->
         <div class="list-article" id="main-list">
          {% for blog in blogs|slice:'6:16' %}
            <!-- single list article  -->
            <article class="card mb-2 bg-white list-card">
              <div class="list-card-wrapper">
                <div class="card-img">
                  <img data-src="{{ blog.photo_main.url }}" alt="">
                </div>
                <div class="card-body">
                  <p class="category">
                    <i class="fas fa-fire-alt"></i>
                    {{ blog.category }}
                  </p>
                  <a href="{% url 'blog:article' blog.category blog.slug %}" class="card-title">
                    <h2>{{ blog.title|title }}
                    </h2>
                  </a>
                  <p class="card-text">
                    {{ blog.description }}
                  </p>
                  <small class="time mb-2"> <i class="far fa-clock"></i>{{ blog.list_date|naturaltime }}</small>
                </div>
              </div>
            </article>
            <!-- end of single list article -->
          {% endfor %}

         </div>
      </div>

      <div class="aside-content">
        
        <div class="list-article">
          <!-- Trending -->
          <div id="trending-list" class="bg-white mb-2 sider">
            <h2 class="trending-title">
              <i class="fas fa-chart-line"></i> Trending
            </h2>
            <div class="card news">
              {% show_trendings %}

            </div>
          </div>
          <!-- End of trending -->
        </div>
      </div>
    </div>
  </main>

{% endblock %}

{% block ajax %} <script src="{% static 'js/cat_load.js' %}"></script> {% endblock %}

blog/templates/blog/data.html
{% load humanize %}
{% for post in posts %}
    <article class="card mb-2 bg-white list-card">
        <div class="list-card-wrapper">
        <div class="card-img">
            <img src="{{ post.photo_main.url }}" alt="">
        </div>
        <div class="card-body">
            <p class="category">
            <i class="fas fa-fire-alt"></i>
            {{ post.category }}
            </p>
            <a href="{% url 'blog:article' post.category post.slug %}" class="card-title">
            <h2>{{ post.title }}
            </h2>
            </a>
            <p class="card-text">
            {{ post.description }}
            </p>
            <small class="time"> <i class="far fa-clock"></i> {{ post.list_date|naturaltime }}</small>
        </div>
        </div>
    </article>
    {% empty %}
    {% if last %}
        {{ last }}
    {% endif %}
    
{% endfor %}

blog/templates/blog/fake-news.html
{% extends 'base.html' %} 
{% load static %} 
{% load humanize %} 
{% load trendings %} 
{% block content %}

<main id="tribune-content" class="wrapper container-fluid">
  <div class="content-wrapper bg-white">
    <!-- main content -->
    <div class="main-content">
      <form id="fake-news-form" method="GET">
        <textarea
          class="form-control"
          name="news"
          id="news"
          cols="30"
          rows="10"
          required
        ></textarea>
        <button type="submit" style="border-radius: 4px; background: rgb(225, 59, 59); border: none; color: white; padding: 10px 20px; cursor: pointer; margin-top: 20px;">Check</button>
      </form>

      <div style="margin-top: 10px; font-size: 21px">
        <p style="color: rgb(255, 59, 59); font-weight: bold; margin-bottom: 10px;">Result: </p>
        <hr />
        <div id="fake-news-result" style="margin-top: 10px; display: flex; flex-direction: column; gap: 5px">

          <p>Linear Regression: </p>
          <p>Decision Tree: </p>
          <p>Gradient Boosting: </p>
          <p>Random Forest: </p>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

{% block ajax %}

<script>
  const form = document.querySelector('#fake-news-form');
  console.log(form);

  form.addEventListener('submit', async e => {
    e.preventDefault();

    const text = document.querySelector('#news').value;
    console.log(text);

    const response = await fetch(`http://127.0.0.1:8000/predict/?text=${text}`, {
      method: 'GET',
    })

    const data = await response.json();

    if (!data) return;

    const result = document.querySelector('#fake-news-result');

    result.innerHTML = `
      <p>Linear Regression: ${data.LR}</p>
      <p>Decision Tree: ${data.DT}</p>
      <p>Gradient Boosting: ${data.GB}</p>
      <p>Random Forest: ${data.RF}</p>
    `
    
  })
</script>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load trendings %}
{% block content %}
    
<main id="tribune-content" class="wrapper container-fluid">
  <div class="content-wrapper">
      <div class="main-content">
        <!-- Main Featured Card big one -->
        <article class="card mb-2 bg-white featured-card">
            <div class="card-img">
              <img data-src="{{ blogs.0.photo_main.url }}" alt="">
            </div>
            <div class="card-body">
              <a href="{% url 'blog:article' blogs.0.category blogs.0.slug %}" class="card-title featured-card-title">
                <h2>
                  {{ blogs.0.title|title }} 
                </h2>
              </a>
            </div>
        </article>
        <!-- end of main featured card -->

        <!-- list media article Hot Topics-->
        <div class="article-listing">
          {% for blog in blogs|slice:"1:5" %}
            <!-- single list article  -->
            <article class="card mb-2 bg-white list-card">
              <div class="list-card-wrapper">
                <div class="card-img">
                  <img data-src="{{ blog.photo_main.url }}" alt="">
                </div>
                <div class="card-body">
                  <p class="category">
                    <i class="fas fa-fire-alt"></i>
                    {{ blog.category }}
                  </p>
                  <a href="{% url 'blog:article' blog.category blog.slug %}" class="card-title">
                    <h2>{{ blog.title|title|truncatechars:50 }}
                    </h2>
                  </a>
                  <p class="card-text">
                    {{ blog.description }}
                  </p>
                  <small class="time mb-2"> <i class="far fa-clock"></i> {{ blog.list_date|naturaltime }}</small>
                </div>
              </div>
            </article>
            <!-- end of single list article -->
          {% endfor %}
            <!-- end of list media article -->
          </div>
          <!-- end of list media -->

        <!-- List with border and title -->
          <div class="promotional bg-white">
            <h3 class="list-title bg-white">
              <i class="fas fa-fire"></i>
              Hot Topics
            </h3>
            <div class="promotional-articles">
              <div class="promotional-content-wrapper">
                {% show_trendings %}
              </div>
              
            </div>
          </div>
        <!-- End of lsit with border and title -->

        <!-- list media article 2 -->
        <div class="article-listing">
          <!-- single list article  -->
          {% for blog in blogs|slice:"5:10" %}
            <article class="card mb-2 bg-white list-card">
            <div class="list-card-wrapper">
              <div class="card-img">
                <img data-src="{{ blog.photo_main.url }}" alt="">
              </div>
              <div class="card-body">
                <p class="category">
                  <i class="fas fa-fire-alt"></i>
                  {{ blog.category }}
                </p>
                <a href="{% url 'blog:article' blog.category blog.slug %}" class="card-title">
                  <h2>{{ blog.title|title }}
                  </h2>
                </a>
                <p class="card-text">
                  {{ blog.description }}
                </p>
                <small class="time mb-2"> <i class="far fa-clock"></i> {{ blog.list_date|naturaltime }}</small>
              </div>
            </div>
            </article>
          {% endfor %}
        <!-- end of single list article -->
        <!-- end of list media article -->
      </div>
      <!-- end of list media -->

      <!-- List with border and title -->
      <div class="promotional bg-white">
        <h3 class="list-title bg-white">
          <i class="fas fa-fire"></i>
          Recent
        </h3>
        <div class="promotional-articles">
          <div class="promotional-content-wrapper">
            {% for blog in blogs|slice:':3' %}
              <!-- Single promotional article -->
              <article class="card mb-2">
                <div class="card-img">
                  <img data-src="{{ blog.photo_main.url }}" alt="">
                </div>
                <div class="card-body">
                  <a class="card-title" href="{% url 'blog:article' blog.category blog.slug %}">
                    <h2>{{ blog.title|truncatechars:50 }}</h2>
                  </a>
                </div>
              </article>
              <!-- end of single promotinal article -->
            {% endfor %}
            


          </div>
          
        </div>
      </div>
    <!-- End of lsit with border and title -->

    <!-- list media article 2 -->
    <div class="article-listing">
      {% for blog in blogs|slice:"10:15" %}
            <article class="card mb-2 bg-white list-card">
            <div class="list-card-wrapper">
              <div class="card-img">
                <img data-src="{{ blog.photo_main.url }}" alt="">
              </div>
              <div class="card-body">
                <p class="category">
                  <i class="fas fa-fire-alt"></i>
                  {{ blog.category }}
                </p>
                <a href="{% url 'blog:article' blog.category blog.slug %}" class="card-title">
                  <h2>{{ blog.title }}
                  </h2>
                </a>
                <p class="card-text">
                  {{ blog.description }}
                </p>
                <small class="time mb-2"> <i class="far fa-clock"></i> {{ blog.list_date|naturaltime }}</small>
              </div>
            </div>
            </article>
        {% endfor %}  


    </div>

    <!-- List with border and title -->
    <div class="promotional bg-white mb-2">
      <h3 class="list-title bg-white">
        <i class="fas fa-fire"></i>
        Tribunes Pick
      </h3>
      <div class="promotional-articles">
        <div class="promotional-content-wrapper">
          {% for trending in trendings|slice:'3:' %}
              <!-- Single promotional article -->
              <article class="card mb-2">
                <div class="card-img">
                  <img data-src="{{ trending.photo_main.url }}" alt="">
                </div>
                <div class="card-body">
                  <a class="card-title" href="{% url 'blog:article' trending.category trending.slug %}">
                    <h2>{{ trending.title|truncatechars:50 }}</h2>
                  </a>
                </div>
              </article>
              <!-- end of single promotinal article -->
            {% endfor %}

        </div>
        
      </div>
    </div>
  <!-- End of lsit with border and title -->
    

    <div class="article-listing" id="main-list">      
      {% for blog in blogs|slice:"15:" %}
        <article class="card mb-2 bg-white list-card">
      <div class="list-card-wrapper">
        <div class="card-img">
          <img data-src="{{ blog.photo_main.url }}" alt="">
        </div>
        <div class="card-body">
          <p class="category">
            <i class="fas fa-fire-alt"></i>
            {{ blog.category }}
          </p>
          <a href="{% url 'blog:article' blog.category blog.slug %}" class="card-title">
            <h2>{{ blog.title }}
            </h2>
          </a>
          <p class="card-text">
            {{ blog.description }}
          </p>
          <small class="time mb-2"> <i class="far fa-clock"></i> {{ blog.list_date|naturaltime }}</small>
        </div>
      </div>
        </article>
    {% endfor %}
  </div>
    
    <!-- end of list media -->

  </div> <!-- content wrapper -->

      <div class="aside-content">
        <div id="checkout" class="bg-white sider">
            <h2 class="news-title">
              Latest News
            </h2>
          <div class=" news">
            <ul class="news-list">
              {% for blog in blogs|slice:':4' %}
                <li class="latest-news-item">
                  <a href="{% url 'blog:article' blog.category blog.slug %}">
                  {{ blog.title|title }} 
                  </a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        
        <!-- Trending -->
        <div id="trending-list" class="bg-white mb-2 sider">
          <h2 class="trending-title">
            <i class="fas fa-chart-line"></i> Trending
          </h2>
          <div class="card news">
            {% show_trendings %}
          </div>
        </div>
        <!-- End of trending -->

      </div>
    </div>

  </main>

{% endblock %}

{% block ajax %} <script src="{% static 'js/blog_load.js' %}"></script> {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>Tribune States | World's No.1 News Portal Site</title>
    <!-- Change Later -->
    <link
      rel="shortcut icon"
      href="{% static 'images/title.png' %}"
      type="image/x-icon"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="anonymous"
    />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <style>
      textarea {
        width: 100%;
        padding: 10px;
        color: #333;
        font-size: 21px;
        font-family: inherit;
        outline: 2px;
        outline-color: cyan;
      }
    </style>

    
  </head>
  <body>
    {% include 'partials/_header.html' %} 
    {% block content %} {%endblock %} 
    {% include 'partials/_footer.html' %}

    <!-- Jquery Cdn -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <!-- custom js -->
    <script src="{% static 'js/app.js' %}"></script>
    {% block ajax %} {% endblock %}
  </body>
</html>

templates/partials/_footer.html
    <footer id="footer">
        <div class="footer-wrapper">
          <div class="footer-contact-info">
            <h2>TRIBUNE STATES</h2>
            <div class="footer-phone">
              <i class="fas fa-phone"></i>
              +123 456 789
            </div>
            <div class="footer-email">
              <i class="fas fa-envelope-open"></i>
              tribunestates@email.com
            </div>
            <div class="footer-web">
              <i class="fas fa-globe"></i>
              tribunestates.com
            </div>
          </div>
  
          <!--lists -->
          <div class="footer-lists">
            <div class="first-section">
              <ul>
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'blog:category' 'politics' %}">Politics</a></li>
                <li><a href="{% url 'blog:category' 'agriculture' %}">Agriculture</a></li>
              </ul>
            </div>
            <div class="second-section">
              <ul>
                <li><a href="{% url 'blog:category' 'science' %}">Science</a></li>
                <li><a href="{% url 'blog:category' 'food' %}">Food</a></li>
                <li><a href="{% url 'blog:category' 'sports' %}">Sports</a></li>
              </ul>
            </div>
            <div class="third-section">
              <ul>
                <li><a href="{% url 'blog:category' 'lifestyle' %}">Lifestyle</a></li>
                <li><a href="{% url 'blog:category' 'environment' %}">Environment</a></li>
                <li><a href="{% url 'blog:category' 'culture' %}">Culture</a></li>
              </ul>
            </div>
          </div>
        </div>
  
        <h3 class="copyright-marker">
          Tribune States. Copyright &copy; 2020.
        </h3>
        
      </footer>
  

templates/partials/_header.html
{% load static %}
{% load trendings %}
<header id="header">
    <nav id="nav">
      <div id="branding">
        <!-- nav button -->
        <div class="nav-toggler">
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
        </div>
        <!-- end of nav button -->
        <a href="{% url 'blog:index' %}"><span>TRIBUNE STATES</span></a>
      </div>

      <!-- nav items -->
      <ul class="nav-items">
        <li class="nav-link"><a href="{% url 'blog:index' %}">Home</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'politics' %}">Politics</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'agriculture' %}">Agriculture</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'science' %}">Sicence</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'food' %}">Food</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'sports' %}">Sports</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'lifestyle' %}">Lifestyle</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'environment' %}">Environment</a></li>
        <li class="nav-link"><a href="{% url 'blog:category' 'culture' %}">Culture</a></li>
      </ul>

      <div id="nav-right-items">
        <button id="search-btn">
          <i class="fas fa-search"></i>
        </button>
      </div>

      <div id="search-dropdown">
        <div class="search-content-wrapper">
          <!-- search form -->
          <form action="{% url 'blog:search' %}" class="search-form">
            <input type="text" name="q" id="search" placeholder="Search on Tribune States...">
            <button type="submit">
              <i class="fas fa-search"></i>
            </button>
          </form>
          <!-- end of search form -->
          <h3 class="search-suggestion-title">
            Trending Topics on Tribute States:
          </h3>
          {% show_trending_list 5 %}
        </div>
      </div>
    </nav>
    <!-- end of navbar -->

    <div id="scroll-progress-bar"></div>

  </header>

templates/partials/_trending_title.html
<ul class="popular-searches">
    {% for trending in trendings %}
        <li class="popular-search">
            <a href="{% url 'blog:article' trending.category trending.slug %}">{{ trending.title }}</a>
      </li>
    {% endfor %}
    
  </ul>

templates/partials/_trendings.html
{% load static %}

{% for trending in trendings %}
    <!-- Single promotional article -->
    <article class="card mb-2">
    <div class="card-img">
        <img data-src="{{ trending.photo_main.url }}" alt="">
    </div>
    <div class="card-body">
        <a class="card-title" href="{% url 'blog:article' trending.category trending.slug %}">
        <h2>{{ trending.title|truncatechars:50|title }} </h2>
        </a>
    </div>
    </article>
    <!-- end of single promotinal article -->
{% endfor %}